#system("python3 Hex/Lib/Aquarium.py")
#system("python3 Hex/Lib/Errors.py")
#system("python3 Hex/Lib/Hex.py")
#system("python3 Hex/Lib/HexREPL.py")
#system("python3 Hex/Lib/Htime.py")
#system("python3 Hex/Lib/UnrealTimeClock.py")