[tool.poetry]
name = "PyHex"
version = "0.1.0"
description = "The Hex programming language"
authors = ["GoodCoderBadBoy"]

[tool.poetry.dependencies]
python = "^3.8"
replit = "^3.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
